package org.weftkit.wiring.processor;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.tools.Diagnostic;

class RegistryGenerator {

    private static final String TEMPLATE = """
            package ${package};

            import java.util.List;
            import java.util.Map;
            import java.util.Optional;
            import java.util.Set;
            import java.util.function.Function;
            import org.weftkit.wiring.runtime.ComponentRegistry;
            import org.weftkit.wiring.runtime.Dependency;

            // Generated by ${generator}
            @SuppressWarnings("unchecked")
            public final class WiredComponents implements ComponentRegistry {

                public static final ComponentRegistry INSTANCE = new WiredComponents();

                private static final List<Class<?>> LOAD_ORDER = List.of(
            ${loadOrder});

                private static final Set<Class<?>> LAZY_SINGLETONS = Set.of(
            ${lazySingletons});

                private static final Map<Class<?>, List<Dependency>> PARAMETERS = Map.ofEntries(
            ${parameters});

                private static final Map<Class<?>, Function<Object[], Object>> FACTORIES = Map.ofEntries(
            ${factories});

                private static final Map<Class<?>, Map<String, Class<?>>> PRODUCT_OWNERS = Map.ofEntries(
            ${productOwners});

                private static final Map<Class<?>, Map<String, Function<Object, Object>>> PRODUCT_GETTERS = Map.ofEntries(
            ${productGetters});

                private static final Map<Class<?>, Map<String, Class<?>>> BINDINGS = Map.ofEntries(
            ${bindings});

                private WiredComponents() {}

                @Override
                public List<Class<?>> loadOrder() {
                    return LOAD_ORDER;
                }

                @Override
                public Set<Class<?>> lazySingletons() {
                    return LAZY_SINGLETONS;
                }

                @Override
                public Map<Class<?>, List<Dependency>> parameters() {
                    return PARAMETERS;
                }

                @Override
                public Map<Class<?>, Function<Object[], Object>> factories() {
                    return FACTORIES;
                }

                @Override
                public Map<Class<?>, Map<String, Class<?>>> productOwners() {
                    return PRODUCT_OWNERS;
                }

                @Override
                public Map<Class<?>, Map<String, Function<Object, Object>>> productGetters() {
                    return PRODUCT_GETTERS;
                }

                @Override
                public Map<Class<?>, Map<String, Class<?>>> bindings() {
                    return BINDINGS;
                }
            }
            """;

    private final WiringModel model;

    private final String registryPackage;

    RegistryGenerator(WiringModel model, String registryPackage) {
        this.model = model;
        this.registryPackage = registryPackage;
    }

    void write(ProcessingEnvironment processingEnv, Element... originating) {
        try (Writer writer = processingEnv
                .getFiler()
                .createSourceFile(registryPackage + ".WiredComponents", originating)
                .openWriter()) {
            writer.write(render());
        } catch (IOException ex) {
            processingEnv
                    .getMessager()
                    .printMessage(Diagnostic.Kind.ERROR, "Failed to generate component registry: " + ex.getMessage());
        }
    }

    private String render() {
        String source = TEMPLATE;
        Map<String, String> sections = Map.of(
                "package", registryPackage,
                "generator", WiredProcessor.class.getName(),
                "loadOrder", loadOrderEntries(),
                "lazySingletons", lazyEntries(),
                "parameters", parameterEntries(),
                "factories", factoryEntries(),
                "productOwners", productOwnerEntries(),
                "productGetters", productGetterEntries(),
                "bindings", bindingEntries());
        for (Map.Entry<String, String> section : sections.entrySet())
            source = source.replace("${" + section.getKey() + "}", section.getValue());
        // Sections contain only class names and quoted qualifiers, so a leftover marker is a template bug
        if (source.contains("${")) throw new IllegalStateException("Unfilled placeholder in the registry template");
        return source;
    }

    private String loadOrderEntries() {
        return block(model.loadOrder().stream().map(singleton -> singleton + ".class"));
    }

    private String lazyEntries() {
        return block(model.lazySingletons().stream().map(singleton -> singleton + ".class"));
    }

    private String parameterEntries() {
        return block(model.components().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, List.<Dependency>of(%s))"
                        .formatted(entry.getKey(), dependencies(entry.getValue().parameters()))));
    }

    private String dependencies(List<WiringModel.Parameter> parameters) {
        return parameters.stream()
                .map(parameter -> "new Dependency(%s.class, %s, %s)"
                        .formatted(parameter.erasedClass(), quote(parameter.qualifier()), parameter.optional()))
                .collect(Collectors.joining(", "));
    }

    private String factoryEntries() {
        return block(model.components().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, arguments -> new %s(%s))"
                        .formatted(
                                entry.getKey(),
                                entry.getKey(),
                                factoryArguments(entry.getValue().parameters()))));
    }

    private String factoryArguments(List<WiringModel.Parameter> parameters) {
        return IntStream.range(0, parameters.size())
                .mapToObj(index -> factoryArgument(parameters.get(index), index))
                .collect(Collectors.joining(", "));
    }

    private String factoryArgument(WiringModel.Parameter parameter, int index) {
        String cast = "(%s) arguments[%d]".formatted(parameter.declaredType(), index);
        return parameter.optional() ? "Optional.ofNullable(" + cast + ")" : cast;
    }

    private String productOwnerEntries() {
        return block(model.products().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, Map.<String, Class<?>>of(%s))"
                        .formatted(
                                entry.getKey(), qualified(entry.getValue(), product -> product.owner() + ".class"))));
    }

    private String productGetterEntries() {
        return block(model.products().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, Map.<String, Function<Object, Object>>of(%s))"
                        .formatted(
                                entry.getKey(),
                                qualified(
                                        entry.getValue(),
                                        product -> "owner -> ((%s) owner).%s()"
                                                .formatted(product.owner(), product.getter())))));
    }

    private String qualified(Map<String, WiringModel.Product> products, Function<WiringModel.Product, String> value) {
        return products.entrySet().stream()
                .map(entry -> "%s, %s".formatted(quote(entry.getKey()), value.apply(entry.getValue())))
                .collect(Collectors.joining(", "));
    }

    private String bindingEntries() {
        return block(model.bindings().entrySet().stream()
                .map(entry -> "Map.entry(%s.class, Map.<String, Class<?>>of(%s))"
                        .formatted(
                                entry.getKey(),
                                entry.getValue().entrySet().stream()
                                        .map(binding ->
                                                "%s, %s.class".formatted(quote(binding.getKey()), binding.getValue()))
                                        .collect(Collectors.joining(", ")))));
    }

    private String block(Stream<String> entries) {
        return entries.collect(Collectors.joining(",\n")).indent(8).stripTrailing();
    }

    // Qualifiers are arbitrary user text, so emit them as properly escaped Java string literals
    private static String quote(String value) {
        StringBuilder quoted = new StringBuilder(value.length() + 2).append('"');
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            switch (character) {
                case '\\' -> quoted.append("\\\\");
                case '"' -> quoted.append("\\\"");
                case '\n' -> quoted.append("\\n");
                case '\r' -> quoted.append("\\r");
                case '\t' -> quoted.append("\\t");
                default -> quoted.append(character);
            }
        }
        return quoted.append('"').toString();
    }
}
