package org.weftkit.wiring.runtime;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;

/**
 * The wiring data generated by the weftkit processor and consumed by {@link WeftLoader}. Product
 * and binding maps are nested by qualifier, with the empty string for unqualified entries. All
 * returned collections must be immutable.
 */
public interface ComponentRegistry {

    List<Class<?>> loadOrder();

    Set<Class<?>> lazySingletons();

    /**
     * Maps a component to the initializer components of its required static holders, created
     * before the component itself is built. Defaults to empty for hand-built registries.
     */
    default Map<Class<?>, List<Class<?>>> requirements() {
        return Map.of();
    }

    Map<Class<?>, List<Dependency>> parameters();

    Map<Class<?>, Function<Object[], Object>> factories();

    Map<Class<?>, Map<String, Class<?>>> productOwners();

    Map<Class<?>, Map<String, Function<Object, Object>>> productGetters();

    Map<Class<?>, Map<String, Class<?>>> bindings();
}
