name: Dependency submission

on:
  push:
    branches: [ main ]

permissions: {}

jobs:

  submit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-java@v5.4.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/dependency-submission@v6.2.0
